---
title: "Civic Analytics Midterm – Part One"
subtitle: "PA 446: Coding for Civic Data Applications"
author: "Ismael Tapia"
date: "`r format(Sys.Date(), '%A • %B %d, %Y')`"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: hide
    highlight: tango
    df_print: paged
    number_sections: false
editor_options:
  markdown:
    wrap: 72
---

PART ONE GITHUB USING R MARKDOWN 


i Describe a civic problem and its implication for the community. Be as
specific as possible.

A civic problem would be the current immigration raid in Chicago as well
as how it is impacting the economy at large in the city. Equally so,
people that were here 20 years ago and have had A clean record is being
deported in large numbers and without due process. This nevertheless,
has impacted families across the board and has led to a mental toll on
our kids' future. Data Science paired with civic technology and public
policy has made a difference. These tools have provided powerful
arguments to why This current immigration policy is not only bad for
Chicago, but the United States as a global powerhouse. The institute on
taxation and economic policy made an analysis explaining a pie chart
that undocumented workers paid a total of 96.7 billion dollars annually.
32.3 billion went to federal social insurance taxes along with state and
local taxes with 37.7 billion dollars, next came in federal income taxes
with 19.6 billion and lastly, misc federal taxes with a grand total of
7.6 billion dollars respectively. The same institute also conducted
another study and it showed a bar chart showing that unauthorized
immigrants paid more of their taxes showing an 8 percent representation
percentage in comparison to the richest 1 percent only paying 5.4
percent. There are also lots of sectors in our economy such as
construction where there are lots of houses left unfinished in Florida
due to fear of deportation and has caused construction companies to lose
money. Recently, Marjorie Taylor Green from the United States house of
representatives was in a podcast expressing her views and said that you
cannot round of every single person you see on the streets who is
undocumented and that she recently became a business owner in the
construction industry.



REFLECTION PART 3 STEP 6 4 QUESTIONS 3-4 SENTENCES 

1) The patterns I see between income and broadband access would be that counties that have an overall higher median incomes will have a greater 
access rate. Moreover, this reveals that there is an upward relationship between income and access to the internet or wifi. In essence, income is the strongest
factor when it comes to digital access in the great state of Illinois. Nonetheless, richer counties have better infrastructure and therefore is a big reason why 
counties that are less rich have less rates of broadband at large. 


2) What will help to explain the variation in broadband access across countries will be the variable of income levels. Moving forward, we can see that population density, infrastructure 
investments all correlate to less broadband access due to rural areas having less providers. If you look at a T-mobile commercial you can see how there are certain rural parts of the 
country where there is no connectivity and Verizon which is an expensive phone and internet provider does. This usually means higher service costs and limited access. Adding on, these factors 
create a hostile equitable market across the state of Illinois as well as not just rural parts of South Dakota as an example. 


3) Public administrators can use this data to inform about digital inclusion policies to look at areas that are the most impacted by their infrastructure; which causes higher costs for coverage 
as well as less wifi providers that offer cheaper or competitive pricing. Moreover, politicians and administrators can look at the data by choosing low income communities as well as rural 
counties within the state of Illinois and expand their proposals for broadband expansion plans and procedures. The data ultimately guides funding, federal grant applications as well as 
evidence that communities need better infrastructure and why Biden felt sorry for kids who did their homework outside a Macdonalds because they did not have reliable internet access at home. 
This led him to pass the infrastructure bill and helped distribute money to different rural areas of the country including Illinois but was no 100 percent fix. 


4)  Some limitations of using CS data for local decision making would be that this type of data set is based on samples and estimates than the complete counts. Equally so, this is concerning 
due to the fact that there exists a margin of error even for smaller areas. Very evidently so, this data is a reflection on past expereinces than the real time issues and conditions.The county 
Broadband quality as well as its speed are not measured and is a huge problem because the speed of wifi is very important. The speed and quality determine if you can get your homework in on time 
as well as be able to review lecture slides or be able to have a tutoring session with your teacher or professor. This can also impact understanding and impacts school performances. Lastly even
if there are challenges in this data set, the ACS data gives valuable data for decision making when it comes to policy and planning when reviewed with extra precautions. 



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




