---
title: "web-scraping.Rmd"
author: "Ismael Tapia"
date: "2025-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r web scrapping}

library(tidyverse)
library(rvest)
library(tibble)

html <- read_html("https://www.scrapethissite.com/pages/simple/")
html





```

```{r}
block <- html |>
  html_elements("div.col-md-4.country")
block


```
```{r}
country_name <- html |>
  html_elements("h3.country-name") |>
  html_text2()
country_name
```

```{r}


Countries_capital <- html |>
  html_elements("span.country-capital") |>
  html_text2()
Countries_capital
```

```{r}
Countries_population <- html |>
  html_elements("span.country-population") |>
  html_text2()
Countries_population

```

```{r}

Countries_total_area <- html |>
  html_elements("span.country-area") |>
  html_text2()
Countries_total_area
```





```{r}
library(tibble)


library(tibble)
countries_table <- tibble(
  country_name = country_name,
  Countries_capital = Countries_capital,
  Countries_population = Countries_population,
  Countries_total_area = Countries_total_area
)

countries_table



```




